-- CREAR LA BASE DE DATOS

use master;
go

create database venta_autos
GO

-- Activar la BD

USE venta_autos;
GO

-- tabla: MARCA

CREATE TABLE MARCA(
	IDMARCA INT NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CONSTRAINT PK_MARCA PRIMARY KEY(IDMARCA),
	CONSTRAINT U_MARCA_NOMBRE UNIQUE(NOMBRE)
);
GO

INSERT INTO MARCA(IDMARCA,NOMBRE) VALUES(1,'TOYOTA');
GO

INSERT INTO MARCA(IDMARCA,NOMBRE) VALUES(2,'HYUNDAI');
GO

SELECT * FROM MARCA;
GO

-- Tabla MODELO

CREATE TABLE MODELO(
	IDMODELO INT NOT NULL, -- PRIMARY KEY
	IDMARCA  INT NOT NULL, -- FOREIGN KEY
	NOMBRE   VARCHAR(100) NOT NULL,
	CONSTRAINT PK_MODELO PRIMARY KEY(IDMODELO),
	CONSTRAINT FK_MODELO_MARCA
		FOREIGN KEY(IDMARCA) REFERENCES MARCA
);
GO

INSERT INTO MODELO(IDMODELO,IDMARCA,NOMBRE) VALUES(100,1,'Corolla');
GO

INSERT INTO MODELO(IDMODELO,IDMARCA,NOMBRE) VALUES(200,2,'Tucson');
GO

INSERT INTO MODELO(IDMODELO,IDMARCA,NOMBRE) VALUES(201,2,'Kona');
GO


SELECT * FROM MODELO;
GO


-- Tabla AUTO

CREATE TABLE AUTO(
	IDAUTO INT NOT NULL IDENTITY(1,1),
	IDMODELO INT NOT NULL,
	DECRIPCION VARCHAR(500) NOT NULL,
	PRECIO NUMERIC(12,2) NOT NULL,
	STOCK INT NOT NULL
);

ALTER TABLE AUTO
ADD CONSTRAINT PK_AUTO PRIMARY KEY(IDAUTO);
GO

ALTER TABLE AUTO
ADD CONSTRAINT FK_AUTO_MODELO
FOREIGN KEY(IDMODELO) REFERENCES MODELO;
GO



